// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvwISF9JTXqPIhJIDkqoVuEXn8zROnQ60',
    appId: '1:1055509999220:web:313dad7422739f8970ab21',
    messagingSenderId: '1055509999220',
    projectId: 'ai-mic-18768',
    authDomain: 'ai-mic-18768.firebaseapp.com',
    storageBucket: 'ai-mic-18768.firebasestorage.app',
    measurementId: 'G-WPRLHTVQWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBvJ9fsDdo-JWlxCMR8LcAICgtouwDIEU',
    appId: '1:1055509999220:android:f06093610d8177c570ab21',
    messagingSenderId: '1055509999220',
    projectId: 'ai-mic-18768',
    storageBucket: 'ai-mic-18768.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHz58mIJXreclXdS1vMN0D6NatZkeZcgQ',
    appId: '1:1055509999220:ios:2d81ac34d6e49b6570ab21',
    messagingSenderId: '1055509999220',
    projectId: 'ai-mic-18768',
    storageBucket: 'ai-mic-18768.firebasestorage.app',
    iosClientId:
        '1055509999220-6qqol075q01edgsjib30h4i3ppt27ce6.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiMic',
  );
}
